version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/store-5
permissions:
  - object: /home/ubuntu/
    pattern: '**'
    mode: 755
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_deploy.sh
      timeout: 300
      runas: ubuntu
